# Collection Decision Tree
# Converted from draw.io — edit layout in D2 as needed.

direction: down

classes: {
  decision: {
    shape: diamond
    width: 250
    height: 250
  }

  decision_dependency: {
    label: "Dependency Acceptable?"
  }

  arrow: {
    style: {
      font-size: 20
      italic: false
      bold: true
    }
  }

  collection_type: {
    shape: rectangle
    width: 200
    height: 70
  }

  collection: {
    shape: rectangle
    width: 200
    height: 70
    style: {
      border-radius: 100
    }
  }
}

start: "Start Here" {
  notice: |md
    - Author: David Fiedler
    - License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    - Repository and Issues: [GitHub](https://github.com/F-I-D-O/Diagrams)
  |
  style: {
    border-radius: 100
  }
}
start -> index_or_not



dict: dict
dict.shape: rectangle

index_or_not: Do you need \n index->value mapping? \n (searching in collection, ...) {
  class: decision
}
index_or_not -> index_type: Yes {
  class: arrow
}
index_or_not -> contains_needed: No {
  class: arrow
}

index_type: Index Type: {
  class: decision
}
index_type -> is_size_constant: Natural numbers, \n all/most indexes are used. {
  class: arrow
}
index_type -> kdtree: Distance to point {
  class: arrow
}
index_type -> rtree: Distance to line or shape {
  class: arrow
}
index_type -> ordered_keys_needed: General {
  class: arrow
}

contains_needed: Frequent need of checking \n if the collection contains \n some member? {
  class: decision
}
contains_needed -> is_set_iteration_needed: Yes {
  class: arrow
}
contains_needed -> fast_removal_needed: No {
  class: arrow
}

is_size_constant: Fixed size? {
  class: decision
}
is_size_constant -> heterogenous_values: Yes {
  class: arrow
}
is_size_constant -> dynamic_array_continuous_memory: No (C++, Python) {
  class: arrow
}
is_size_constant -> java_dynamic_array_continuous_memory_dependency_acceptable: No (Java) {
  class: arrow
}

kdtree: KDTree {
  class: collection_type
}

rtree: RTree {
  class: collection_type
}

ordered_keys_needed: Do you need the keys \n to be ordered? {
  class: decision
}
ordered_keys_needed -> tree_map: Yes {
  class: arrow
}
ordered_keys_needed -> is_map_iteration_needed: No {
  class: arrow
}

is_set_iteration_needed: Iteration or \n determinism needed? {
  class: decision
}
is_set_iteration_needed -> linked_set: Yes {
  class: arrow
}
is_set_iteration_needed -> set: No {
  class: arrow
}

fast_removal_needed: Do you need to remove \n from the collection often? {
  class: decision
}
fast_removal_needed -> removal_type: Yes {
  class: arrow
}
fast_removal_needed -> is_size_constant: No {
  class: arrow
}

heterogenous_values: Heterogenous value types? {
  class: decision
}
heterogenous_values -> tuple: Yes {
  class: arrow
}
heterogenous_values -> java_record: Yes, Java {
  class: arrow
}
heterogenous_values -> is_member_default_constructible: No {
  class: arrow
}

dynamic_array_continuous_memory: Dynamic array with \n continuous memory {
  class: collection_type
}
dynamic_array_continuous_memory -> fastutils: Java {
  class: arrow
}
dynamic_array_continuous_memory -> python_array: Python {
  class: arrow
}
dynamic_array_continuous_memory -> std_vector: C++ {
  class: arrow
}

dynamic_array_non_continuous_memory: Dynamic array with \n non-continuous memory {
  class: collection_type
}
dynamic_array_non_continuous_memory -> python_list: Python {
  class: arrow
}
dynamic_array_non_continuous_memory -> array_list: Java {
  class: arrow
}


java_dynamic_array_continuous_memory_dependency_acceptable {
  class: [decision; decision_dependency]
}
java_dynamic_array_continuous_memory_dependency_acceptable -> dynamic_array_continuous_memory: Yes {
  class: arrow
}
java_dynamic_array_continuous_memory_dependency_acceptable -> memory_critical_and_primitive_members: No {
  class: arrow
}

tree_map: Ordered/tree map {
  class: collection_type
}
tree_map -> std_map: C++ {
  class: arrow
}
tree_map -> tree_map_java: Java {
  class: arrow
}

is_map_iteration_needed: Do you need to \n iteration or determinism? {
  class: decision
}
is_map_iteration_needed -> hash_map: No {
  class: arrow
}
is_map_iteration_needed -> linked_hash_map: Yes {
  class: arrow
}

linked_set: Linked set {
  class: collection_type
}
linked_set -> linked_hash_set: Java {
  class: arrow
}
linked_set -> boost_multi_index: C++ {
  class: arrow
}

set: Set {
  class: collection_type
}
set -> hashset: Java {
  class: arrow
}
set -> python_set: Python {
  class: arrow
}
set -> std_unordered_set: C++ {
  class: arrow
}

removal_type: Removal Type: {
  class: decision
}
removal_type -> queue: FIFO {
  class: arrow
}
removal_type -> linked_list: Neighboring indicies {
  class: arrow
}
removal_type -> dynamic_array_continuous_memory: Neighboring indicies, Python {
  class: arrow
}
removal_type -> dynamic_array_continuous_memory: Random {
  class: arrow
}

tuple: Tuple {
  class: collection_type
}
tuple -> python_tuple: Python {
  class: arrow
}
tuple -> is_pair: C++ {
  class: arrow
}

array: Array {
  class: collection_type
}
array -> numpy_array: Python {
  class: arrow
}
array -> std_array: C++ {
  class: arrow
}
array -> java_array: Java {
  class: arrow
}

is_member_default_constructible: Default-constructible members? {
  class: decision
}
is_member_default_constructible -> array: Yes {
  class: arrow
}
is_member_default_constructible -> dynamic_array_continuous_memory: No {
  class: arrow
}

std_vector: std::vector {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/vector
}

python_list: "[]" {
  class: collection
  link: https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range
}

array_list: ArrayList {
  class: collection
  link: https://docs.oracle.com/en/java/javase/26/docs/api/java.base/java/util/ArrayList.html
}

memory_critical_and_primitive_members: Memory critical \n AND \n primitive members \n (int, float)? {
  class: decision
}
memory_critical_and_primitive_members -> array: Yes {
  class: arrow
}
memory_critical_and_primitive_members -> dynamic_array_non_continuous_memory: No {
  class: arrow
}

std_map: std::map {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/map
}

tree_map_java: TreeMap {
  class: collection
  link: https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/TreeMap.html
}

hash_map: Dictionary/hash map {
  class: collection_type
}
hash_map -> hash_map_java: Java {
  class: arrow
}
hash_map -> dict: Python {
  class: arrow
}
hash_map -> unordered_map: C++ {
  class: arrow
}

linked_hash_map: Linked hash map {
  class: collection_type
}
linked_hash_map -> linked_hash_map_java: Java {
  class: arrow
}
linked_hash_map -> boost_multi_index: C++ {
  class: arrow
}

linked_hash_set: LinkedHashSet {
  class: collection
  link: https://docs.oracle.com/javase/26/docs/api/java/util/LinkedHashSet.html
}

boost_multi_index: boost::multi_index {
  class: collection
  link: https://www.boost.org/doc/libs/latest/libs/multi_index/doc/index.html
}

hashset: HashSet {
  class: collection
  link: https://docs.oracle.com/javase/26/docs/api/java/util/HashSet.html
}

std_unordered_set: std::unordered_set {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/unordered_set
}

queue: Queue {
  class: collection_type
}
queue -> std_queue: C++ {
  class: arrow
}
queue -> python_queue: Python {
  class: arrow
}

linked_list: Linked list {
  class: collection_type
}
linked_list -> linked_list_java: Java {
  class: arrow
}
linked_list -> std_list: C++ {
  class: arrow
}

python_tuple: tuple {
  class: collection
  link: https://docs.python.org/3/library/stdtypes.html#tuple
}

is_pair: Just two objects? {
  class: decision
}
is_pair -> std_pair: Yes {
  class: arrow
}
is_pair -> std_tuple: No {
  class: arrow
}

numpy_array: numpy.array {
  class: collection
  link: https://numpy.org/doc/stable/reference/generated/numpy.array.html
}

std_array: std::array {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/array
}

java_array: "[]" {
  class: collection
  link: https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/ArrayList.html
}

hash_map_java: HashMap {
  class: collection
  link: https://docs.oracle.com/en/java/javase/26/docs/api/java.base/java/util/HashMap.html
}

unordered_map: std::unordered_map {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/unordered_map
}

linked_hash_map_java: LinkedHashMap {
  class: collection
  link: https://docs.oracle.com/en/java/javase/26/docs/api/java.base/java/util/LinkedHashMap.html
}

std_queue: std::queue {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/queue
}

python_queue: queue.Queue {
  class: collection
  link: https://docs.python.org/3/library/queue.html
}

linked_list_java: LinkedList {
  class: collection
  link: https://docs.oracle.com/en/java/javase/26/docs/api/java.base/java/util/LinkedList.html
}

std_list: std::list {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/list
}

std_pair: std::pair {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/pair
}

std_tuple: std::tuple {
  class: collection
  link: https://en.cppreference.com/w/cpp/container/tuple
}

java_record: Record {
  class: collection
  link: https://docs.oracle.com/en/java/javase/26/language/records.html
}

python_array: "[]" {
  class: collection
  link: https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range
}








